name = "google-drive-index"
compatibility_date = "2026-01-02"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "drive-index-db"
database_id = "905f8060-0f68-4d50-ba03-eb7ab116b3f0"